<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '68a5717c5d0686d15a5fb0617298246b',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/oc_projets_n8?serverVersion=5.7.19',
);
